# Generated by Django 4.2 on 2025-05-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certification", "0003_alter_certification_technical_devices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certification",
            name="technical_devices",
            field=models.TextField(verbose_name="Технические устройства"),
        ),
    ]
